version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "QazXsw12345#@!"
    ports:
      - "1433:1433"
  game:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mssql