// <auto-generated />
using System;
using GameHelperApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameHelperApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220420202427_Hardware_Second")]
    partial class Hardware_Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("GameHelperApp.Models.Engines", b =>
                {
                    b.Property<int>("EngineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EngineLogo")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("EngineId");

                    b.ToTable("Engines");
                });

            modelBuilder.Entity("GameHelperApp.Models.Games", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Cover")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("EnginesEngineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Genre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudiosStudioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId");

                    b.HasIndex("EnginesEngineId");

                    b.HasIndex("StudiosStudioId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameHelperApp.Models.Studios", b =>
                {
                    b.Property<int>("StudioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyDescriptiopn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Country")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Logo")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumberOfWorkers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("YearOfEstablishment")
                        .HasColumnType("TEXT");

                    b.HasKey("StudioId");

                    b.ToTable("Studios");
                });

            modelBuilder.Entity("GameHelperApp.Models.Games", b =>
                {
                    b.HasOne("GameHelperApp.Models.Engines", "Engines")
                        .WithMany()
                        .HasForeignKey("EnginesEngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameHelperApp.Models.Studios", "Studios")
                        .WithMany()
                        .HasForeignKey("StudiosStudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engines");

                    b.Navigation("Studios");
                });
#pragma warning restore 612, 618
        }
    }
}
